# render.yaml – Blueprint für BookReview (API + Web), .NET 9, Docker
services:
  - type: web
    name: bookreview-api
    env: docker
    plan: free
    region: frankfurt
    rootDir: .
    dockerfilePath: src/BookReview.Api/Dockerfile
    autoDeploy: true
    healthCheckPath: /api/books

  - type: web
    name: bookreview-web
    env: docker
    plan: free
    region: frankfurt
    rootDir: .
    dockerfilePath: src/BookReview.Web/Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: API_HOST
        fromService:
          type: web
          name: bookreview-api
          property: host
      - key: API_SCHEME
        value: https
