name: Docker build & push to GHCR

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ghcr-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive lowercase owner/name
        id: names
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ steps.names.outputs.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- API IMAGE ---
      - name: Docker meta (api)
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ steps.names.outputs.OWNER_LC }}/${{ steps.names.outputs.REPO_NAME }}-api
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & push (api)
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/BookReview.Api/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- WEB IMAGE ---
      - name: Docker meta (web)
        id: meta_web
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ steps.names.outputs.OWNER_LC }}/${{ steps.names.outputs.REPO_NAME }}-web
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & push (web)
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/BookReview.Web/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
